### ISSUE TITLE
実行確認アラートを no_dry_run チェックボックスの状態によって出し分けたい

### ISSUE THREAD

**Issue by yutailang0119** [uzulla/yet-another-bulk-mailer#4]

**Comment by yutailang0119** [comment]
https://github.com/uzulla/yet-another-bulk-mailer/blob/master/index.php#L11 をいじるといい感じがするのですが、サジェスチョンもらえれば対応します！

**Comment by uzulla** [comment]
はい！そこでチェックボックスの状態をみればOKだと思います！
(jsは適当にかいちゃってOKです)

**Comment by uzulla** [comment]
@yutailang0119 
機能追加しておきました。

私のポリシー的にダイアログはいずれでも出します、ただしメッセージが明確になるようにしました。

**Comment by yutailang0119** [comment]
はい！ボクがやってもそうなったと思います！
ありがとうございます 🙇
