### ISSUE TITLE
{{name}}の展開を件名にも適応する

### ISSUE THREAD

**Issue by yutailang0119** [uzulla/yet-another-bulk-mailer#5]

**Comment by uzulla** [comment]
![image](https://user-images.githubusercontent.com/870716/61573298-046e1000-aae7-11e9-9bde-d732db2332ae.png)

**Comment by uzulla** [comment]
機能追加しておきました @yutailang0119

**Comment by yutailang0119** [comment]
ありがとうございます 🙇
